### ISSUE TITLE
Installation issue (npm run build)

### ISSUE THREAD

**Issue by annalina** [ASQ-USI/ASQ#119]
I get the following error when I run "npm run build)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/annalina/.nvm/versions/node/v4.0.0/bin/node" "/Users/annalina/.nvm/versions/node/v4.0.0/bin/npm" "run" "build"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2

npm ERR! missing script: build
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/annalina/WORKDIR/installation/ASQ/npm-debug.log

Here the log:

0 info it worked if it ends with ok
1 verbose cli [ '/Users/annalina/.nvm/versions/node/v4.0.0/bin/node',
1 verbose cli   '/Users/annalina/.nvm/versions/node/v4.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose stack Error: missing script: build
4 verbose stack     at run (/Users/annalina/.nvm/versions/node/v4.0.0/lib/node_modules/npm/lib/run-script.js:142:19)
4 verbose stack     at /Users/annalina/.nvm/versions/node/v4.0.0/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /Users/annalina/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/Users/annalina/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/Users/annalina/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/Users/annalina/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at /Users/annalina/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:300:12
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (evalmachine.<anonymous>:380:3)
5 verbose cwd /Users/annalina/WORKDIR/installation/ASQ
6 error Darwin 15.6.0
7 error argv "/Users/annalina/.nvm/versions/node/v4.0.0/bin/node" "/Users/annalina/.nvm/versions/node/v4.0.0/bin/npm" "run" "build"
8 error node v4.0.0
9 error npm  v2.14.2
10 error missing script: build
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

Thank you

**Comment by triglian** [comment]
Hello @annalina, I will try to update the installation guide over the weekend.

This is still a research project and we need to make it a bit more user friendly, so bear with us 🙂

**Comment by stephenhutt** [comment]
I'm having a similar issue, just wondering if this was ever resolved? Not been able to do the docker installation either, so tried the manual, but hit this problem

**Comment by VincenzoFerme** [comment]
@triglian please give a look at this issue.
@stephenhutt could you more details about the issue you are facing?
