### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by kbj804** [ASQ-USI/ASQ#49]
I try 'npm start' 
error 'npm-debug.log'

0 info it worked if it ends with ok
1 verbose cli [ '/home/kbj/.nvm/versions/node/v4.0.0/bin/node',
1 verbose cli   '/home/kbj/.nvm/versions/node/v4.0.0/bin/npm',
1 verbose cli   'start' ]
2 info using npm@2.14.2
3 info using node@v4.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart asq@0.3.0-alpha
6 info start asq@0.3.0-alpha
7 verbose unsafe-perm in lifecycle true
8 info asq@0.3.0-alpha Failed to exec start script
9 verbose stack Error: asq@0.3.0-alpha start: `NODE_ENV=production node -r dotenv/config app.js dotenv_config_silent=true`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/home/kbj/.nvm/versions/node/v4.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/home/kbj/.nvm/versions/node/v4.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:817:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid asq@0.3.0-alpha
11 verbose cwd /home/kbj/Test/ASQ
12 error Linux 3.19.0-25-generic
13 error argv "/home/kbj/.nvm/versions/node/v4.0.0/bin/node" "/home/kbj/.nvm/versions/node/v4.0.0/bin/npm" "start"
14 error node v4.0.0
15 error npm  v2.14.2
16 error code ELIFECYCLE
17 error asq@0.3.0-alpha start: `NODE_ENV=production node -r dotenv/config app.js dotenv_config_silent=true`
17 error Exit status 1
18 error Failed at the asq@0.3.0-alpha start script 'NODE_ENV=production node -r dotenv/config app.js dotenv_config_silent=true'.
18 error This is most likely a problem with the asq package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     NODE_ENV=production node -r dotenv/config app.js dotenv_config_silent=true
18 error You can get their info via:
18 error     npm owner ls asq
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by triglian** [comment]
Hello,

I assume you have gone through the [installation guide](https://github.com/ASQ-USI/ASQ/blob/master/doc/install/installation.md), right?

**Comment by kbj804** [comment]
Hi triglian
yes.. you are right.
OS is Ubuntu
My way is wrong?

**Comment by triglian** [comment]
Sorry for the late reply, can you try this command:

```
NODE_ENV=production node app.js -r dotenv/config app.js dotenv_config_silent=true
```

**Comment by Livinu** [comment]
Hi Triglian, there is an issue in the start command, the slide2html command didn't pass because the ../../slide2html from upload/upload/pdf.js is missing.

/path/to/ASQ npm start

> asq@0.3.0-alpha start 
> NODE_ENV=production node -r dotenv/config app.js dotenv_config_silent=true

module.js:487
    throw err;
    ^

Error: Cannot find module '../../slide2html'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/ASQ/lib/upload/pdf.js:15:20)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/ASQ/lib/upload/upload.js:10:13)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/ASQ/routes/user/presentations/handlers.js:19:16)
    at Module._compile (module.js:569:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! asq@0.3.0-alpha start: `NODE_ENV=production node -r dotenv/config app.js dotenv_config_silent=true`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the asq@0.3.0-alpha start script.

**Comment by Meorge** [comment]
I'm experiencing this same error as well when trying to run `npm start`. Has a solution been found?
